### ISSUE TITLE
ch6 PCB中files初始化问题

### ISSUE THREAD

**Issue by qky18** [DeathWish5/ucore-Tutorial#4]
proc.c中的 `allocproc` 函数是否应该在 [found](https://github.com/DeathWish5/ucore-Tutorial/blob/ch6/kernel/proc.c#L107) 这一行之后添加初始化语句：

```c
memset(&p->files, 0, sizeof(p->files));
```

不添加的话，有可能在 `fdalloc` 里根据 `p->files[i] == 0` 为文件寻找进程中未被分配的fd时出现错误。

（发现这一点是在写lab6的时候静态分配了struct mailbox，本地和CI结果不一致且本地无法复现，然后输出TRACE发现CI中一些本来被期待是0的值不是0……）

**Comment by DeathWish5** [comment]
确实存在这个问题，不过在 free_proc 里有所有清空 files 的操作，不过在 proinit 的时候没有，应该更新 procinit.
马上修复!

**Comment by qky18** [comment]
有道理！进程结束一定会调用 `free_proc` ，所以通过 `allocproc` 继承进程池中已结束进程内存的新进程不会受影响，确实只需要改 `procinit` 就可以了
