### ISSUE TITLE
ch2中pack.py的问题

### ISSUE THREAD

**Issue by penPenf28** [DeathWish5/ucore-Tutorial#6]
中间39行
`'''.format(idx, TARGET_DIR + app)`
要改成
`'''.format(idx, TARGET_DIR +“/”+ app)`
才能正常运行貌似，不然找不到bin文件的目录

**Comment by DeathWish5** [comment]
这样确实稳一点，目前解决方法是 TARGET_DIR 最后多一个 '/'，找个时间统一改一改。
